name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install

            - name: Run lint
              run: bun run lint:all

            - name: Run fmt:check
              run: bun run fmt:check

            - name: Run build
              run: bun run build --if-present

            - name: Run test
              run: bun run test
